name: Deploy to Heroku
on:
  push:	
    branches:	
      - master

jobs:
  deploy:
    name: Deploy to Heroku
    defaults:
     run:
       working-directory: backend
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - name: build ui
      uses: actions/setup-node@v1
      with: 
        node-version: 12.x
    - run: npm install
    - run: npm run build:ui
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: main
        FOLDER: backend
        GITHUB_TOKEN: ${{ secrets.GITHUB }}
